const CONFIG = {
    introTitle: 'Hehe chào trứng ngok',
    introDesc: `Hong biết cậu có chút hong thoải mái nào hong nma cứ chơi cho tớ zui nha`,
    btnIntro: 'hihi',
    title: 'Nghe nói hum nay có người có mụt ngày bận rộn😙',
    desc: 'Cậu có mún vừa nghỉ ngơi vừa nch với tớ hem ',
    btnYes: 'Cóaaaaa',
    btnNo: 'Không, mơ đi ',
    question:'Quick question nè,điều cậu thít nhất ở tớ',
    btnReply: 'THẬt LÒNG NGHEN <3',
    reply: 'Đượttt <33333333',
    mess: 'Hehe bít ngay 🥰. Hubby của cậu mà lại',
    messDesc: 'Last one,đừng quơn kèo giữa chúng ta nhóeee',
    btnAccept: 'Dạaaaaa <3',
}
