const CONFIG = {
    introTitle: 'Chào trứng ngok cụa tớ',
    introDesc: ``,
    btnIntro: 'hihi',
    title: 'Nghe noái hum nay cậu có mụt ngày bận rộn😙',
    desc: 'Cậu có mún chò chiện với tiên nữ tú hemmm ',
    btnYes: 'Có chớ <33',
    btnNo: 'Không,mơ đi :3',
    question:'Quick question nè,cậu thích điều gì nhất ở tớ',
    btnReply: 'Gửi cho tớ nghen <3',
    reply: 'Hmm cũng gọi là cute đới <33333333',
    mess: 'Hehe tớ biết mà 🥰. Hubby của cậu mà lại 😘😘',
    messDesc: 'Nhớ đừng quên kèo giữa chúng ta nghennn.',
    btnAccept: 'Dạaaa <3',
    
